### ISSUE TITLE
Horizontal scroll bar support to Result Analysis page

### ISSUE THREAD

**Issue by kimlep01** [OpenTMI/opentmi-default-gui#106]
I would like to have a horizontal scroll bar in Result Analysis -> Results Pivottable page. I often add several filters to isolate a failure to a certain device and the results go too far to the right out of screen. The only workaround for this is to stretch the browser window larger and move it to the left.

**Comment by jupe** [comment]
I think this is fixed in recent changes. Please reopen/create new ticket if needed.
