### ISSUE TITLE
Request to have test results with an hour resolution in Results Pivottable

### ISSUE THREAD

**Issue by kimlep01** [OpenTMI/opentmi-default-gui#109]
Currently we have option to get test results with a day resolution in Results Pivottable. It would be more useful to have test results with an hour resolution. This way we could easily have the whole night's test results by using a filter: 
Start: HH DD-MM-YYYY
End: HH DD-MM-YYYY

If our nightly test runs are split over to two days it is more difficult to filter them.

**Comment by jupe** [comment]
this is implemented and coming in next release
